export class Vendor{
  constructor(
    public name?: string,
    public position?: string,
    public department?:string,
    public countrycode?:string,
    public phonenumber?:string,
    public linkedin?:string,
    public organization_type?:string,
    public suite?:string,
    public numberstreet?:string,
    public city?:string,
    public state?:string,
    public country?:string,
    public zip?:string,
    public company_name?:string,
    public url?:string,
    public logo?:string,
    public year?:string,
    public mission?:string,
    public founded?:string,
    public size?:string,
    public affiliation?:number,
    public companyphone?:string,
    public taxid?:string,
    public facebook?:string,
    public twitter?:string,
    public line?:string
  ){}
}
